name-template: 'release-v$NEXT_PATCH_VERSION'
tag-template: 'release-v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'docs'
      - 'ci'
      - 'build'
  - title: 'Optimization'
    labels:
      - 'perf'
      - 'style'
      - 'refactor'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  $CHANGES
